In [234]:

import folium
from folium import plugins
import pandas as pd
import numpy as np
from tqdm import tqdm


In [235]:
# m = folium.Map(location=[52.215933,19.134422], zoom_start=6)
m = folium.Map(location=[51.1113305,17.041928], zoom_start=14)
# ic_nodes_coord = pd.read_csv('ic_coord.nodes')
# 
# def removeAccents(text): # encoding works in html, but not in Jupyter view
#     polishChars = 'ąćęłńóśżźĄĆĘŁŃÓŚŻŹ'
#     replace     = 'acelnoszzACELNOSZZ'
#     translator=str.maketrans(polishChars, replace)
#     return text.translate(translator)
# 

In [236]:
en = pd.read_json('data/data_without_date.json').head(10000)
en

x          y  energy_delta  population     traffic
0     51.254420  17.198291    677.555455        10.3  103.529879
1     51.046788  16.985132    407.405404        19.9   75.893818
2     51.054762  16.986780    323.304877        19.9   58.722987
3     51.119808  17.047497    951.273333        34.6   95.318814
4     51.119674  16.869864   1187.938434        28.1   69.992959
...         ...        ...           ...         ...         ...
9995  51.074097  16.982061   1560.015933        19.9   99.936578
9996  51.121481  16.960053    347.084257        33.5   93.217743
9997  51.103874  17.059278   -629.539217        34.6  101.018958
9998  51.168261  16.969580    -33.427517        33.5   75.408896
9999  51.145451  16.854952   -712.894731        28.1   72.302852

[10000 rows x 5 columns]

In [237]:
# locations = en[['x', 'y', 'energy_delta']].to_numpy()
# m.add_children(plugins.HeatMap(locations, radius=20, blur=40))
# 0

In [238]:
gradient_default =  {0.4: 'blue', 0.65: 'lime', 1: 'red'}
radius = 20
blur = 40



In [239]:
en_minus = en[en['energy_delta'] < 0][['x', 'y', 'energy_delta']]
en_minus['energy_delta'] = en_minus.energy_delta.apply(np.abs)

locations_minus = en_minus.to_numpy()
print(locations_minus)
# gradient_minus =  {0.4: 'lightblue', 0.65: 'blue', 1: 'darkblue'}
gradient_minus =  {0.4: 'yellow', 0.65: 'orange', 1: 'red'}
m.add_children(plugins.HeatMap(locations_minus, name='excess energy', radius=radius, blur=blur, gradient=gradient_minus))
# plugins.HeatMap(locations_minus, radius=radius, blur=blur, gradient=gradient_minus).add_to(m)

locations_plus = en[en['energy_delta'] > 0][['x', 'y', 'energy_delta']].to_numpy()
gradient_plus = {0.4: 'lightblue', 0.65: 'blue', 1: 'darkblue'}
# gradient_plus =  {0.4: 'yellow', 0.65: 'orange', 1: 'red'}
m.add_children(plugins.HeatMap(locations_plus, name='energy consumption', radius=radius, blur=blur, gradient=gradient_plus))
# plugins.HeatMap(locations_plus, radius=radius, blur=blur, gradient=gradient_plus).add_to(m)

0

[[ 51.1198186   17.10876358 437.71700336]
 [ 51.15971542  17.08816986 894.37244361]
 [ 51.13664541  17.06329523 286.57803073]
 ...
 [ 51.10387433  17.05927775 629.53921708]
 [ 51.16826059  16.96958026  33.42751726]
 [ 51.14545093  16.85495161 712.894731  ]]


C:\Users\najle\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method `add_children` is deprecated. Please use `add_child` instead.
  
C:\Users\najle\anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Method `add_children` is deprecated. Please use `add_child` instead.
  


0

In [240]:
folium.LayerControl().add_to(m)
m.save('map_test.html')
print('done :D')
# m


done :D


In [241]:
locations_plus


array([[  51.25441969,   17.19829055,  677.55545476],
       [  51.04678837,   16.98513193,  407.40540356],
       [  51.05476208,   16.98678011,  323.30487713],
       ...,
       [  51.1564233 ,   16.82386581,  203.88352584],
       [  51.07409732,   16.98206081, 1560.01593259],
       [  51.12148115,   16.96005323,  347.08425746]])

In [242]:
locations_minus


array([[ 51.1198186 ,  17.10876358, 437.71700336],
       [ 51.15971542,  17.08816986, 894.37244361],
       [ 51.13664541,  17.06329523, 286.57803073],
       ...,
       [ 51.10387433,  17.05927775, 629.53921708],
       [ 51.16826059,  16.96958026,  33.42751726],
       [ 51.14545093,  16.85495161, 712.894731  ]])